### ISSUE TITLE
[MySQL] Can't connect to local MySQL server through socket 

### ISSUE THREAD

**Issue by filiptronicek** [gitpod-io/workspace-images#343]
Hi,
I have set up a simple Apache PHP server with `workspace-full` and `workspace-mysql`, I tried running commands on workspace initialization and I get the following error:
```bash
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```
My `.gitpod.yml`:
```yaml
image:
  file: .gitpod.dockerfile
  context: apache
ports:
- port: 8080
  onOpen: open-preview
tasks:
- name: Terminal
  command: >
    mysql -e "CREATE DATABASE iclip;";
    mysql < scripts/db.sql;
    bash scripts/secrets.sh;
- name: Apache
  command: >
    apachectl start &&
    multitail /var/log/apache2/access.log -I /var/log/apache2/error.log
```

My `.gitpod.Dockerfile`:
```Dockerfile
FROM gitpod/workspace-full:latest
FROM gitpod/workspace-mysql

# optional: use a custom apache config.
COPY apache.conf /etc/apache2/apache2.conf

# optional: change document root folder. It's relative to your git working copy.
ENV APACHE_DOCROOT_IN_REPO="."
```
