### ISSUE TITLE
Custom image based on workspace-full runs 'pyenv shell shims' on every new bash

### ISSUE THREAD

**Issue by heidiLinguist** [gitpod-io/workspace-images#909]
### Bug description

I have a custom image based on workspace-full.  All that does is install the Google Cloud Platform (see below).  After updating the image, I now have two errors:

On startup, I get

`mv: cannot stat '/home/gitpod/.pyenv/version': No such file or directory`

The file does exist--it's a link.

And on every newly opened bash shell, I get:

```
pyenv shell shims
pyenv: version `shims' not installed
```

### Steps to reproduce

.gitpod.Dockerfile:

```
FROM gitpod/workspace-full

# Install Google Cloud SDK
ARG DEBIAN_FRONTEND=noninteractive
ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
RUN echo "set disable_coredump false" >>/tmp/sudo.conf && sudo cp /tmp/sudo.conf /etc/sudo.conf \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - \
    && echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \  
    && sudo apt-get update \
    && sudo apt-get -y install apt-transport-https ca-certificates gnupg \
    && sudo apt-get -y install google-cloud-sdk \
    && sudo rm -rf /var/lib/apt/lists/*
# Removed installation of Python 2.7
```

.gitpod.yml:

```
image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip3 uninstall -y twine && pip3 install -r ./requirements.txt
  - command: pyenv rehash && pyenv version

vscode:
  extensions:
    - ms-azuretools.vscode-docker
```

I'm uninstalling twine in an attempt to resolve a dependency conflict.  The problem happens in any case.

### Expected behavior

I would not expect to see either of these errors.  Not sure if shims are working as expected.

### Anything else?

Love Gitpod, thanks all.
