### ISSUE TITLE
Spike: analyze opportunities to shorten build times for main

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/workspace-images#919]
## Is your feature request related to a problem? Please describe

The [build for main](https://github.com/gitpod-io/workspace-images/actions/workflows/push-main.yml) appears to take between 3 and 5 hours to run. :grimacing: 

In looking at [the most recent successful build for main](https://github.com/gitpod-io/workspace-images/actions/runs/2943862962), it took 4h and 50m:
- dazzle build took 1h 28m
- dazzle combine took 2h 12m
- sync images with docker hub took 1h 8m

## Describe the behaviour you'd like

A quicker loop, so we can iterate more easily. 

## Describe alternatives you've considered

For example, are we effectively using GAR cache with dazzle build and combine, or can that be improved? Is there a more efficient way to push content to Docker Hub...we spend a lot of time syncing, which checks tags that have already been pushed.

**Comment by Siddhant-K-code** [comment]
> For example, are we effectively using GAR cache with dazzle build and combine, or can that be improved? Is there a more efficient way to push content to Docker Hub...we spend a lot of time syncing, which checks tags that have already been pushed.

I don't think, there is much possibility on `Sync Images` step. But, What would happen if we combine the `Dazzle Build & Dazzle Combine` steps as:

```yml

- name: 🔨 Dazzle build & 🖇️ Dazzle combine
  run: |
    dazzle build ${{ env.GAR_IMAGE_REGISTRY }}/gitpod-artifacts/docker-dev/workspace-base-images --chunked-without-hash
    dazzle build ${{ env.GAR_IMAGE_REGISTRY }}/gitpod-artifacts/docker-dev/workspace-base-images
    dazzle combine ${{ env.GAR_IMAGE_REGISTRY }}/gitpod-artifacts/docker-dev/workspace-base-images --all
```

Because, GH Actions doesn't caches b//w the steps. So, I think it would be good to build & combine the chunks in a single step. WDYT?

**Comment by Siddhant-K-code** [comment]
There is no much benefit from the above solution: saved ~8 minutes only 😞 [logs here](https://github.com/gitpod-io/workspace-images/runs/8167540590?check_suite_focus=true)

**Comment by Siddhant-K-code** [comment]
I think we should include the following caching in our main (to at least fasten up the push to main). We can Save & Restore Cache from `main`

```yml
      - name: 🗄️ Force Save Registry Cache of main branch as Per Sha
        uses: actions/cache@v3
        with:
          path: ~/registry
          key: ${{ runner.os }}-main-branch-cache-${{ github.sha }}

      - name: 🗄️ Restore Registry Cache of main branch
        uses: actions/cache@v3
        with:
          path: ~/registry
          key: ${{ runner.os }}-main-branch-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-main-branch-cache-
```

> Ref: [.github/workflows/pull-request.yml#L38-L50](https://github.com/gitpod-io/workspace-images/blob/main/.github/workflows/pull-request.yml#L38-L50)
